name : git workflow
on : push
jobs :
    test-job :
        runs-on : ubuntu-latest
        steps :
            - name : checkout
              uses : actions/checkout@v4
            - name : test job
              run : |
                    echo "welcome all"
                    cat README.md
         